### ISSUE TITLE
mirage-platform disagreggation

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-platform#124]
We should aim to move as much as C stubs as possible to their own repository.

This means:
- [ ] Move [cstruct_stubs](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/cstruct_stubs.c) to [cstruct](https://github.com/mirage/ocaml-cstruct)
- [ ] Move [unsafe_load_uint32](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/barrier_stubs.c#L43), [unsafe_save_uint32](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/barrier_stubs.c#L55) to [cstruct](https://github.com/mirage/ocaml-cstruct)
- [ ] Maybe move [atomic_or_fetch_uint8](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/atomic_stubs.c#L23) and [atomic_fetch_and_uint8](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/atomic_stubs.c#L36) to [cstruct](https://github.com/mirage/ocaml-cstruct)
- [ ] Move [clock_stubs](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/clock_stubs.c) to [mirage-clock](https://github.com/mirage/mirage-clock)
- [ ] Move [eventch_stubs](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/eventchn_stubs.c) to [xen-evtchn](https://github.com/mirage/ocaml-evtchn)
- [ ] Move [gnttab_stubs](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/gnttab_stubs.c) to [xen-gnt](https://github.com/mirage/ocaml-gnt)
- [ ] Move [xb_stubs](https://github.com/mirage/mirage-platform/blob/master/xen-ocaml/bindings/xb_stubs.c) to [xenstore](https://github.com/mirage/ocaml-xenstore/) (or somewhere else which handle the Xenbus protocol)?

**Comment by samoht** [comment]
Note that @pqwy is cleaning up the xen post-conf scripts to make that transition easier.

**Comment by hannesm** [comment]
this is slightly more subtle, [some bits and pieces](https://github.com/mirage/mirage-platform/blob/master/bindings/build.sh#L16-L17) of the bindings subdirectory are built with `-D_INSIDE_MINIOS` while others aren't.

**Comment by talex5** [comment]
As far as I can see,  defining `__INSIDE_MINIOS__` has only two effects:
* It exposes atomic bit operations in `os.h` (`test_and_clear_bit`, etc)
* It does `#define current get_current()` in `sched.h`

It's quite possible we're not using either of these and it can be removed.

Also, it should be safe to remove the `-fno-tree-loop-distribute-patterns -fno-stack-protector` flags now. Mini-OS automatically adds `-fno-stack-protector` to the pkg-config file where needed (x86), and as far as I know `-fno-tree-loop-distribute-patterns` was never needed outside of Mini-OS itself (it's for compiling `memcpy` and similar primitives).

**Comment by hannesm** [comment]
I talked with @mato yesterday and it seems this would be nice to have in order to get the solo5 stuff neatly integrated...  as @samoht mentioned, @pqwy did rewrite [postconf](https://github.com/mirleft/ocaml-nocrypto/blob/master/postconf) in shell (only needed up to line 9 in the general case, see the one in [ocaml-crc](https://github.com/xapi-project/ocaml-crc/blob/master/postconf.sh)... any volunteers? ;)

**Comment by hannesm** [comment]
after some years, I came to the following conclusion:  we leave the C stubs in mirage-xen for now, and once we have a better cross-compilation story, we'll move them elsewhere.  the reason is because cross-compiling C stubs for MirageOS is atm a huge amount of scaffolding, and mirage-xen is always required (similarly, we have the solo5 stubs in mirage-solo5).
